<?php

namespace Database\Seeders;

use App\Models\Product;
use Illuminate\Database\Seeder;

class ProductSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $products = [
            [
                'name' => 'Mele Golden',
                'name_en' => 'Golden apples',
                'description' => 'Mele dolci e croccanti.',
                'description_en' => 'Sweet and crunchy apples.',
                'price' => 2.50,
                'unit_type' => 'kg',
                'is_active' => true,
            ],
            [
                'name' => 'Arance Tarocco',
                'name_en' => 'Tarocco oranges',
                'description' => 'Arance succose di stagione.',
                'description_en' => 'Juicy seasonal oranges.',
                'price' => 2.20,
                'unit_type' => 'kg',
                'is_active' => true,
            ],
            [
                'name' => 'Lattuga',
                'name_en' => 'Lettuce',
                'description' => 'Lattuga fresca.',
                'description_en' => 'Fresh lettuce.',
                'price' => 1.30,
                'unit_type' => 'pz',
                'is_active' => true,
            ],
            [
                'name' => 'Fragole',
                'name_en' => 'Strawberries',
                'description' => 'Vaschetta di fragole fresche.',
                'description_en' => 'Punnet of fresh strawberries.',
                'price' => 3.80,
                'unit_type' => 'vaschetta',
                'is_active' => true,
            ],
            [
                'name' => 'Prezzemolo',
                'name_en' => 'Parsley',
                'description' => 'Mazzo di prezzemolo fresco.',
                'description_en' => 'Bunch of fresh parsley.',
                'price' => 0.90,
                'unit_type' => 'pz',
                'is_active' => true,
            ],
            [
                'name' => 'Banane',
                'name_en' => 'Bananas',
                'description' => 'Banane mature e cremose.',
                'description_en' => 'Ripe and creamy bananas.',
                'price' => 1.80,
                'unit_type' => 'kg',
                'is_active' => true,
            ],
            [
                'name' => 'Pere Abate',
                'name_en' => 'Abate pears',
                'description' => 'Pere dolci dalla polpa morbida.',
                'description_en' => 'Sweet pears with soft flesh.',
                'price' => 2.90,
                'unit_type' => 'kg',
                'is_active' => true,
            ],
            [
                'name' => 'Kiwi',
                'name_en' => 'Kiwis',
                'description' => 'Kiwi verdi ricchi di vitamina C.',
                'description_en' => 'Green kiwis rich in vitamin C.',
                'price' => 3.20,
                'unit_type' => 'kg',
                'is_active' => true,
            ],
            [
                'name' => 'Limoni',
                'name_en' => 'Lemons',
                'description' => 'Limoni profumati non trattati.',
                'description_en' => 'Fragrant untreated lemons.',
                'price' => 2.40,
                'unit_type' => 'kg',
                'is_active' => true,
            ],
            [
                'name' => 'Uva Italia',
                'name_en' => 'Italia grapes',
                'description' => 'Uva bianca dolce e croccante.',
                'description_en' => 'Sweet and crisp white grapes.',
                'price' => 4.50,
                'unit_type' => 'kg',
                'is_active' => true,
            ],
            [
                'name' => 'Pesche Gialle',
                'name_en' => 'Yellow peaches',
                'description' => 'Pesche mature e succose.',
                'description_en' => 'Ripe and juicy peaches.',
                'price' => 3.60,
                'unit_type' => 'kg',
                'is_active' => true,
            ],
            [
                'name' => 'Albicocche',
                'name_en' => 'Apricots',
                'description' => 'Albicocche dolci di stagione.',
                'description_en' => 'Sweet seasonal apricots.',
                'price' => 4.20,
                'unit_type' => 'kg',
                'is_active' => true,
            ],
            [
                'name' => 'Ciliegie',
                'name_en' => 'Cherries',
                'description' => 'Ciliegie rosse e croccanti.',
                'description_en' => 'Red and crunchy cherries.',
                'price' => 7.90,
                'unit_type' => 'kg',
                'is_active' => true,
            ],
            [
                'name' => 'Melone Retato',
                'name_en' => 'Cantaloupe melon',
                'description' => 'Melone retato dolce e profumato.',
                'description_en' => 'Sweet and fragrant cantaloupe melon.',
                'price' => 2.80,
                'unit_type' => 'pz',
                'is_active' => true,
            ],
            [
                'name' => 'Anguria',
                'name_en' => 'Watermelon',
                'description' => 'Anguria fresca e dissetante.',
                'description_en' => 'Fresh and refreshing watermelon.',
                'price' => 1.10,
                'unit_type' => 'kg',
                'is_active' => true,
            ],
            [
                'name' => 'Ananas',
                'name_en' => 'Pineapple',
                'description' => 'Ananas dolce pronto da gustare.',
                'description_en' => 'Sweet pineapple ready to enjoy.',
                'price' => 3.90,
                'unit_type' => 'pz',
                'is_active' => true,
            ],
            [
                'name' => 'Mango',
                'name_en' => 'Mango',
                'description' => 'Mango maturo dalla polpa morbida.',
                'description_en' => 'Ripe mango with soft flesh.',
                'price' => 2.50,
                'unit_type' => 'pz',
                'is_active' => true,
            ],
            [
                'name' => 'Avocado',
                'name_en' => 'Avocado',
                'description' => 'Avocado Hass pronto al consumo.',
                'description_en' => 'Hass avocado ready to eat.',
                'price' => 2.20,
                'unit_type' => 'pz',
                'is_active' => true,
            ],
            [
                'name' => 'Pomodori Ramati',
                'name_en' => 'Vine tomatoes',
                'description' => 'Pomodori ramati maturati al sole.',
                'description_en' => 'Sun-ripened vine tomatoes.',
                'price' => 2.70,
                'unit_type' => 'kg',
                'is_active' => true,
            ],
            [
                'name' => 'Pomodorini Ciliegino',
                'name_en' => 'Cherry tomatoes',
                'description' => 'Pomodorini dolci in vaschetta.',
                'description_en' => 'Sweet cherry tomatoes in a punnet.',
                'price' => 2.90,
                'unit_type' => 'vaschetta',
                'is_active' => true,
            ],
            [
                'name' => 'Zucchine',
                'name_en' => 'Courgettes',
                'description' => 'Zucchine verdi fresche.',
                'description_en' => 'Fresh green courgettes.',
                'price' => 2.30,
                'unit_type' => 'kg',
                'is_active' => true,
            ],
            [
                'name' => 'Melanzane',
                'name_en' => 'Aubergines',
                'description' => 'Melanzane viola dalla polpa soda.',
                'description_en' => 'Purple aubergines with firm flesh.',
                'price' => 2.60,
                'unit_type' => 'kg',
                'is_active' => true,
            ],
            [
                'name' => 'Peperoni Rossi',
                'name_en' => 'Red peppers',
                'description' => 'Peperoni rossi dolci e carnosi.',
                'description_en' => 'Sweet and fleshy red peppers.',
                'price' => 3.40,
                'unit_type' => 'kg',
                'is_active' => true,
            ],
            [
                'name' => 'Carote',
                'name_en' => 'Carrots',
                'description' => 'Carote fresche e croccanti.',
                'description_en' => 'Fresh and crunchy carrots.',
                'price' => 1.60,
                'unit_type' => 'kg',
                'is_active' => true,
            ],
            [
                'name' => 'Patate Novelle',
                'name_en' => 'New potatoes',
                'description' => 'Patate novelle a pasta gialla.',
                'description_en' => 'Yellow-fleshed new potatoes.',
                'price' => 1.90,
                'unit_type' => 'kg',
                'is_active' => true,
            ],
            [
                'name' => 'Cipolle Dorate',
                'name_en' => 'Yellow onions',
                'description' => 'Cipolle dorate dal gusto delicato.',
                'description_en' => 'Mild-flavoured yellow onions.',
                'price' => 1.70,
                'unit_type' => 'kg',
                'is_active' => true,
            ],
            [
                'name' => 'Aglio',
                'name_en' => 'Garlic',
                'description' => 'Aglio fresco italiano.',
                'description_en' => 'Fresh Italian garlic.',
                'price' => 1.20,
                'unit_type' => 'pz',
                'is_active' => true,
            ],
            [
                'name' => 'Broccoli',
                'name_en' => 'Broccoli',
                'description' => 'Broccoli verdi appena raccolti.',
                'description_en' => 'Freshly picked green broccoli.',
                'price' => 2.80,
                'unit_type' => 'kg',
                'is_active' => true,
            ],
            [
                'name' => 'Cavolfiore',
                'name_en' => 'Cauliflower',
                'description' => 'Cavolfiore bianco compatto.',
                'description_en' => 'Compact white cauliflower.',
                'price' => 2.50,
                'unit_type' => 'pz',
                'is_active' => true,
            ],
            [
                'name' => 'Spinaci',
                'name_en' => 'Spinach',
                'description' => 'Spinaci freschi da cuocere.',
                'description_en' => 'Fresh spinach for cooking.',
                'price' => 2.20,
                'unit_type' => 'kg',
                'is_active' => true,
            ],
            [
                'name' => 'Bietole',
                'name_en' => 'Swiss chard',
                'description' => 'Mazzo di bietole tenere.',
                'description_en' => 'Bunch of tender Swiss chard.',
                'price' => 1.80,
                'unit_type' => 'pz',
                'is_active' => true,
            ],
            [
                'name' => 'Finocchi',
                'name_en' => 'Fennel',
                'description' => 'Finocchi croccanti dal sapore aromatico.',
                'description_en' => 'Crisp fennel with an aromatic flavour.',
                'price' => 2.10,
                'unit_type' => 'kg',
                'is_active' => true,
            ],
            [
                'name' => 'Sedano',
                'name_en' => 'Celery',
                'description' => 'Sedano verde da cucina.',
                'description_en' => 'Green celery for cooking.',
                'price' => 1.50,
                'unit_type' => 'pz',
                'is_active' => true,
            ],
            [
                'name' => 'Porri',
                'name_en' => 'Leeks',
                'description' => 'Porri freschi dal gusto delicato.',
                'description_en' => 'Fresh leeks with a mild flavour.',
                'price' => 2.70,
                'unit_type' => 'kg',
                'is_active' => true,
            ],
            [
                'name' => 'Funghi Champignon',
                'name_en' => 'Button mushrooms',
                'description' => 'Funghi champignon freschi affettati.',
                'description_en' => 'Fresh sliced button mushrooms.',
                'price' => 2.80,
                'unit_type' => 'vaschetta',
                'is_active' => true,
            ],
            [
                'name' => 'Rucola',
                'name_en' => 'Rocket salad',
                'description' => 'Rucola fresca dal gusto intenso.',
                'description_en' => 'Fresh rocket salad with a bold flavour.',
                'price' => 1.50,
                'unit_type' => 'kg',
                'is_active' => true,
            ],
            [
                'name' => 'Basilico',
                'name_en' => 'Basil',
                'description' => 'Mazzo di basilico profumato.',
                'description_en' => 'Bunch of fragrant basil.',
                'price' => 1.10,
                'unit_type' => 'pz',
                'is_active' => true,
            ],
            [
                'name' => 'Menta',
                'name_en' => 'Mint',
                'description' => 'Mazzo di menta fresca.',
                'description_en' => 'Bunch of fresh mint.',
                'price' => 1.10,
                'unit_type' => 'pz',
                'is_active' => true,
            ],
            [
                'name' => 'Noci',
                'name_en' => 'Walnuts',
                'description' => 'Noci sgusciate selezionate.',
                'description_en' => 'Selected shelled walnuts.',
                'price' => 4.90,
                'unit_type' => 'kg',
                'is_active' => true,
            ],
            [
                'name' => 'Mandorle',
                'name_en' => 'Almonds',
                'description' => 'Mandorle pelate croccanti.',
                'description_en' => 'Crunchy blanched almonds.',
                'price' => 5.20,
                'unit_type' => 'kg',
                'is_active' => true,
            ],
            [
                'name' => 'Mirtilli',
                'name_en' => 'Blueberries',
                'description' => 'Mirtilli freschi in vaschetta.',
                'description_en' => 'Fresh blueberries in a punnet.',
                'price' => 3.50,
                'unit_type' => 'vaschetta',
                'is_active' => true,
            ],
            [
                'name' => 'Lamponi',
                'name_en' => 'Raspberries',
                'description' => 'Lamponi delicati e dolci.',
                'description_en' => 'Delicate and sweet raspberries.',
                'price' => 3.90,
                'unit_type' => 'vaschetta',
                'is_active' => true,
            ],
            [
                'name' => 'More',
                'name_en' => 'Blackberries',
                'description' => 'More fresche dal gusto intenso.',
                'description_en' => 'Fresh blackberries with a bold flavour.',
                'price' => 3.90,
                'unit_type' => 'vaschetta',
                'is_active' => true,
            ],
            [
                'name' => 'Clementine',
                'name_en' => 'Clementines',
                'description' => 'Clementine senza semi e profumate.',
                'description_en' => 'Fragrant seedless clementines.',
                'price' => 2.60,
                'unit_type' => 'kg',
                'is_active' => true,
            ],
            [
                'name' => 'Pompelmo Rosa',
                'name_en' => 'Pink grapefruit',
                'description' => 'Pompelmo rosa fresco e succoso.',
                'description_en' => 'Fresh and juicy pink grapefruit.',
                'price' => 2.80,
                'unit_type' => 'kg',
                'is_active' => true,
            ],
            [
                'name' => 'Radicchio',
                'name_en' => 'Radicchio',
                'description' => 'Radicchio rosso croccante.',
                'description_en' => 'Crunchy red radicchio.',
                'price' => 2.40,
                'unit_type' => 'pz',
                'is_active' => true,
            ],
            [
                'name' => 'Cavolo Nero',
                'name_en' => 'Tuscan kale',
                'description' => 'Cavolo nero ideale per zuppe.',
                'description_en' => 'Tuscan kale ideal for soups.',
                'price' => 2.60,
                'unit_type' => 'kg',
                'is_active' => true,
            ],
            [
                'name' => 'Zucca Butternut',
                'name_en' => 'Butternut squash',
                'description' => 'Zucca dolce dalla polpa compatta.',
                'description_en' => 'Sweet squash with firm flesh.',
                'price' => 2.30,
                'unit_type' => 'kg',
                'is_active' => true,
            ],
            [
                'name' => 'Cetrioli',
                'name_en' => 'Cucumbers',
                'description' => 'Cetrioli freschi e croccanti.',
                'description_en' => 'Fresh and crunchy cucumbers.',
                'price' => 1.90,
                'unit_type' => 'kg',
                'is_active' => true,
            ],
            [
                'name' => 'Fagiolini',
                'name_en' => 'Green beans',
                'description' => 'Fagiolini verdi teneri.',
                'description_en' => 'Tender green beans.',
                'price' => 3.80,
                'unit_type' => 'kg',
                'is_active' => true,
            ],
            [
                'name' => 'Piselli',
                'name_en' => 'Peas',
                'description' => 'Piselli freschi già sgranati.',
                'description_en' => 'Fresh shelled peas.',
                'price' => 3.50,
                'unit_type' => 'vaschetta',
                'is_active' => true,
            ],
            [
                'name' => 'Mais Dolce',
                'name_en' => 'Sweetcorn',
                'description' => 'Pannocchie di mais dolce fresco.',
                'description_en' => 'Fresh sweetcorn cobs.',
                'price' => 1.40,
                'unit_type' => 'pz',
                'is_active' => true,
            ],
            [
                'name' => 'Barbabietole Rosse',
                'name_en' => 'Beetroots',
                'description' => 'Barbabietole rosse cotte al vapore.',
                'description_en' => 'Steam-cooked red beetroots.',
                'price' => 2.10,
                'unit_type' => 'kg',
                'is_active' => true,
            ],
        ];

        foreach ($products as $product) {
            Product::updateOrCreate(['name' => $product['name']], $product);
        }
    }
}
